[Time]
NTP=time.google.com pool.ntp.org time.cloudflare.com time.nist.gov
FallbackNTP=ntp.ubuntu.com time1.google.com time2.google.com time3.google.com time4.google.com
RootDistanceMaxSec=1
PollIntervalMinSec=64
PollIntervalMaxSec=1024
SaveIntervalSec=60
